include ../make/Makefile.inc
include ../make/Makefile_tex.inc

# LATEX_FLAGS := \def\showmargins{}

## Генериране на устав и учредителен протокол
ngo-creation-docs: $(BUILD_DIR)/creation/устав.pdf $(BUILD_DIR)/creation/учредителен-протокол.pdf

clean: ## Clean build directory
	@rm -rf build
