include ../make/Makefile.inc
include ../make/Makefile_tex.inc

# LATEX_FLAGS := \def\showmargins{}

## Генериране на устав и учредителен протокол
statutes: build/устав.pdf build/учредителен-протокол.pdf

clean: ## Clean build directory
	@rm -rf $(BUILD_DIR)
