name: Build PDF and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - '*tex*'
      - 'statute'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Compile latex documents
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: docs
          root_file: |
            устав.tex
            учредителен-протокол.tex

      - name: Prepare dist folder with PDFs
        run: |
          mkdir -p wrapper_dist/dist
          mv docs/*.pdf wrapper_dist/dist/

      - name: Upload generated PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdfs
          path: wrapper_dist/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: generated-pdfs
          path: wrapper_dist/

      - name: Deploy for Cloudflare
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wrapper_dist
          publish_branch: serve-pdfs-${{ github.ref_name }}
          force_orphan: true
          commit_message: |
            Deploy generated PDFs from ${{ github.ref_name }}
            ${{ github.event.head_commit.message }}
